version: "3.9"
services:
  song-service-postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: denis
      POSTGRES_PASSWORD: denis
      POSTGRES_DB: song_service
